# This is a basic workflow to help you get started with Actions

name: "Azure Bicep Demo Environment"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  AzureBicepDeploy:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
    #Login to Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_Login }}
    #Deploy Bicep File
    - name: Azure Bicep Build
      run: |
        az bicep build --file ./main.bicep
        
    - name: Az CLI Create Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ secrets.Azure_RG }} --location ${{ env.ResourceGroupLocation }}

    - name: Deploy Azure Bicep
      uses: Azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ secrets.Azure_RG }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: ./main.json 
